name: start
description: Starter Arcade application using recommended code generation libraries
version: 1.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  arcade: ^0.2.3+1
  envied: ^1.0.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  luthor: ^0.4.3

dev_dependencies:
  build_runner: ^2.4.13
  envied_generator: ^1.0.0
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0
  lint: ^2.3.0
  luthor_generator: ^0.5.0
