name: start
description: Starter Arcade application using recommended code generation libraries
version: 1.0.0

environment:
  sdk: ^3.0.6

dependencies:
  arcade: ^0.1.0+1
  envied: ^0.3.0+3
  get_it: ^7.6.0
  injectable: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  injectable_generator: ^2.1.6
  lint: ^2.1.2
  test: ^1.21.0
