name: start
description: Starter Arcade application using recommended code generation libraries
version: 1.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  arcade: ^0.3.2
  arcade_cache: ^0.0.2
  arcade_cache_redis: ^0.0.2
  arcade_swagger: ^0.0.5
  drift: ^2.27.0
  drift_postgres: ^1.3.1
  envied: ^1.1.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  luthor: ^0.6.0
  meta: ^1.17.0
  postgres: ^3.5.6
  superclass: ^0.1.0

dev_dependencies:
  build_runner: ^2.5.4
  drift_dev: ^2.27.0
  envied_generator: ^1.1.1
  freezed: ^3.0.3
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  lint: ^2.8.0
  luthor_generator: ^0.7.0
  superclass_generator: ^0.4.0
