name: start
description: Starter Arcade application using recommended code generation libraries
version: 1.0.0

environment:
  sdk: ^3.0.6

dependencies:
  arcade: ^0.1.2
  envied: ^0.5.2
  get_it: ^7.6.4
  injectable: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.7
  envied_generator: ^0.5.2
  injectable_generator: ^2.4.1
  lint: ^2.3.0
  test: ^1.25.0
