name: start
description: Starter Arcade application using recommended code generation libraries
version: 1.0.0

environment:
  sdk: ^3.0.6

dependencies:
  arcade: ^0.1.2
  envied: ^0.5.2
  get_it: ^7.7.0
  injectable: ^2.4.2

dev_dependencies:
  build_runner: ^2.4.11
  envied_generator: ^0.5.4
  injectable_generator: ^2.6.1
  lint: ^2.3.0
