name: start
description: Starter Arcade application using recommended code generation libraries
version: 1.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  arcade: ^0.2.1
  envied: ^0.5.2
  get_it: ^8.0.1
  injectable: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.13
  envied_generator: ^0.5.4
  injectable_generator: ^2.6.1
  lint: ^2.3.0
