name: start
description: Starter Arcade application using recommended code generation libraries
version: 1.0.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  arcade: ^0.3.1
  envied: ^1.1.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  luthor: ^0.6.0

dev_dependencies:
  build_runner: ^2.4.15
  envied_generator: ^1.1.1
  freezed: ^3.0.3
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4
  lint: ^2.8.0
  luthor_generator: ^0.7.0
