name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dpk
        shell: bash
        run: dart install dpk

      - name: Add Dart bin to PATH
        shell: bash
        run: echo "$HOME/.local/state/Dart/install/bin" >> $GITHUB_PATH

      - name: Get dependencies
        shell: bash
        run: dart pub get

      - name: Run format
        shell: bash
        run: dpk run ci:format

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dpk
        shell: bash
        run: dart install dpk

      - name: Add Dart bin to PATH
        shell: bash
        run: echo "$HOME/.local/state/Dart/install/bin" >> $GITHUB_PATH

      - name: Get dependencies
        shell: bash
        run: dart pub get

      - name: Copy .env.example to .env
        shell: bash
        run: cp .env.example .env

      - name: Run build
        shell: bash
        run: dpk run build

      - name: Run analyze
        shell: bash
        run: dpk run ci:analyze
